import { html } from 'lit'
export default (self) => html`<div class="mui-panel mui--text-title">Zephyrus Gyro Stabilization</div>
<div class="mui-panel"><div class="badge" style="${self._badgeStyle()}">${self._statusText()}</div><br/><br/><table class="mui-table mui-table--bordered"><tbody><tr><td><b>Sensor</b></td><td>MPU6050 (GY-521)</td></tr><tr><td><b>Bus</b></td><td>I²C (GPIO1=SDA, GPIO3=SCL)</td></tr><tr><td><b>Sample Rate</b></td><td>200 Hz</td></tr><tr><td><b>AHRS Algorithm</b></td><td>Mahony</td></tr>${self.gyroEnabled ? html`<tr><td><b>Uptime</b></td><td>${self._uptimeLabel()}</td></tr>` : null}</tbody></table></div>
${self.gyroEnabled ? html`<div class="mui-panel"><div class="mui--text-title" style="font-size:14px;">MPU Mounting Orientation</div><select class="mui-select" style="width:100%;margin-top:8px;" @change="${self._setOrientation}">${self._rotationOptions().map(opt => html`<option value="opt.val" ?selected="${self._isRotation(opt.val)}">${opt.label}</option>`)}</select><small style="color:#888; display:block; margin-top:6px;">Select how the GY-521 is physically mounted. Roll/pitch should read 0° when level.</small></div>` : null}
${self.gyroEnabled ? html`<div class="mui-panel"><div class="mui--text-title" style="font-size:16px;">Live Telemetry</div><table class="mui-table mui-table--bordered"><tbody><tr><td><b>Roll</b></td><td>${self._fmtDeg(self.rollDeg)}</td><td><b>Roll Corr</b></td><td>${self._fmt1(self.rollCorrection)}</td></tr><tr><td><b>Pitch</b></td><td>${self._fmtDeg(self.pitchDeg)}</td><td><b>Pitch Corr</b></td><td>${self._fmt1(self.pitchCorrection)}</td></tr><tr><td><b>Yaw Rate</b></td><td>${self._fmtDegPS(self.yawRate)}</td><td><b>Yaw Corr</b></td><td>${self._fmt1(self.yawCorrection)}</td></tr><tr><td colspan="2"><b>Rudder µs</b></td><td colspan="2">${self._fmt1(self.rudderCorrection)}</td></tr></tbody></table></div>` : null}
<div class="mui-panel" style="text-align:center;"><div class="attitude-indicator" style="font-size:12px; color:#888; margin-bottom:8px;">Attitude Indicator</div><div class="pteronautos-horizon" style="${self._horizonOuterStyle()}"><div class="horizon-line" style="${self._horizonLineStyle()}"><div class="center-dot" style="${self._centerDotStyle()}"></div></div></div><small style="color:#888; display:block; margin-top:8px;">${self._horizonCaption()}</small></div>
<div># PID Controllers — Roll / Pitch / Yaw with Feed Forward</div>
${axes = [ {id:'roll', label:'Roll', p:self.rollP,i:self.rollI,d:self.rollD,max:self.rollMax,ff:self.rollFF}, {id:'pitch', label:'Pitch', p:self.pitchP,i:self.pitchI,d:self.pitchD,max:self.pitchMax,ff:self.pitchFF}, {id:'yaw', label:'Yaw', p:self.yawP,i:self.yawI,d:self.yawD,max:self.yawMax,ff:self.yawFF} ]}
${axes.map(axis => html`<div class="mui-panel"><div class="mui--text-title" style="font-size:16px;">${"#{axis.label} Axis PID"}</div><table class="mui-table mui-table--bordered"><tbody><tr><td><b>P (Proportional)</b></td><td><input type="range" min="0" max="100" value="axis.p" style="width:150px;" @input="${self._onSlider("#{axis.id}P")}"/>${axis.p}</td></tr><tr><td><b>I (Integral)</b></td><td><input type="range" min="0" max="100" value="axis.i" style="width:150px;" @input="${self._onSlider("#{axis.id}I")}"/>${axis.i}</td></tr><tr><td><b>D (Derivative)</b></td><td><input type="range" min="0" max="100" value="axis.d" style="width:150px;" @input="${self._onSlider("#{axis.id}D")}"/>${axis.d}</td></tr><tr><td><b>Max Correction</b></td><td><input type="range" min="0" max="100" value="axis.max" style="width:150px;" @input="${self._onSlider("#{axis.id}Max")}"/>${axis.max}%</td></tr><tr><td><b>Feed Forward</b><br/><small style="color:#888;">Stick bypass ratio</small></td><td><input type="range" min="0" max="100" value="axis.ff" style="width:150px;" @input="${self._onSlider("#{axis.id}FF")}"/>${axis.ff}%</td></tr></tbody></table></div>`)}
<div class="mui-panel" style="text-align:center;"><button class="mui-btn mui-btn--primary" @click="${self._doCalibrate}" ?disabled="${self._calibDisabled()}">${self._calibrateLabel()}</button>${self._calibrating ? html`<br/><small style="color:#da0;">${self._calibProgress()}</small>` : null}<br/><small style="color:#888;">${self._calibHint()}</small></div>`