# encoding: utf-8
require "rake/clean"
require "json"
require "haml"

LANGS = %w[pt en ru es de ja zh]
SUBFOLDERS = %w[en ru es de ja zh]

CLOBBER.include("index.html", *SUBFOLDERS.map { |d| "#{d}/index.html" }, "assets/css/style.css")

def build_html(lang)
  vars = JSON.parse(File.read("_lang/#{lang}.json", encoding: "UTF-8"))
  template = File.read("index.haml", encoding: "UTF-8")
  engine = Haml::Template.new { template }
  output = engine.render(Object.new, vars)

  out_path = lang == "pt" ? "index.html" : "#{lang}/index.html"
  File.write(out_path, output, encoding: "UTF-8")
  puts "  Built #{out_path} (#{lang.upcase})"
end

desc "Build Haml to HTML (#{LANGS.map(&:upcase).join(' + ')})"
task :haml do
  LANGS.each { |lang| build_html(lang) }
end

desc "Build Sass to CSS"
task :sass do
  sh "bundle exec sass assets/css/style.sass assets/css/style.css"
end

desc "Build all"
task build: [:haml, :sass]

desc "Clean and build"
task rebuild: [:clobber, :build]

task default: :build
